1k:
	python apriori.py /Users/Rozen_mac/code/mining/Week2/APhw_demo/T10I10N0.1KD1K.data 4
10k:
	python apriori.py /Users/Rozen_mac/code/mining/Week2/APhw_demo/T20I15N1KD10K.data 9
100k:
	python apriori.py /Users/Rozen_mac/code/mining/Week2/APhw_demo/T12I30N0.5KD100K.data 300
500k:
	python apriori.py /Users/Rozen_mac/code/mining/Week2/APhw_demo/T18I20N2KD5000K.data 65000
